_merge = "shallow"
home = ["html", "rss", "jsonfeed", "archives", "offline", "search"]
page = ["html", "markdown"]
section = ["html", "rss", "jsonfeed"]
taxonomy = ["html"]
term = ["html", "rss", "jsonfeed"]
