
[customPartials]
  head = [
    "inject/fixit-docs-bookmark.html",
    "inject/component-projects.html",
    "inject/shortcode-rewards.html",
    ]
  menuDesktop = [
    "inject/translate-menu-desktop.html",
    ]
    menuMobile = [                                            "inject/translate-menu-mobile.html",                  ]
    profile = []
    aside = []
    comment = []
    footer = []
    widgets = []
    assets = [
      "inject/cmpt-flyfish.html",
      "inject/cmpt-mdevtools.html",
      "inject/cmpt-translate.html",
      "inject/shortcode-caniuse.html",
    ]
    postFooterBefore = []
    postFooterAfter = []



  # FixIt component (fixit-bundle)
  # cmpt-flyfish
  [params.flyfish]
    enable = true
    light = "rgb(0 119 190 / 10%)"
    dark = "rgb(255 255 255 / 10%)"

  # Mobile Devtools config
  [params.mDevtools]
    enable = false
    # "eruda", "vConsole" supported
    type = "eruda"

  [params.autoTranslate]
    enable = true
    service = 'client.edge'
    languages = []
    ignoreID = []
    ignoreClass = []
    ignoreTag = []
    detectLocalLanguage = false
    cdn = ""
  
  [params.projectsAdapters]
    enable = false
    onlyPublic = true
    categories = []
    collections = []
    ignoreList = []
    [params.projectsAdapters.params]
      hiddenFromHomePage = true
      # more font matter here ...